# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
#
# ThinkPad P16s Gen 2 (AMD Ryzen 7 PRO 7840U)
# NOTE: Update UUIDs after fresh NixOS installation with disko
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
  { device = "/dev/disk/by-uuid/cedb32d6-0812-4232-a0e2-10b498a1fc32";
    fsType = "ext4";
  };

  fileSystems."/boot" =
  { device = "/dev/disk/by-uuid/5405-DB45";
    fsType = "vfat";
    options = [ "fmask=0022" "dmask=0022" ];
  };

  fileSystems."/data" =
  { device = "/dev/disk/by-uuid/a066731b-569c-4f21-aac7-571156eb8979";
    fsType = "ext4";
  };

  # Note: Update swap UUID after disko formatting
  # swapDevices = [
  #   { device = "/dev/disk/by-uuid/SWAP-UUID-HERE"; }
  # ];

  networking.useDHCP = lib.mkDefault true;

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
